#!/bin/sh

# main paths
export PATH=$RICEDDARIOHOME/lib:$RICEDDARIOHOME/sequence:$RICEDDARIOHOME/web_services:$RICEDDARIOHOME/job_scheduling:$RICEDDARIOHOME/QUEST:$RICEDDARIOHOME/structure:$RICEDDARIOHOME/WORKFLOW:$PATH
export PERL5LIB=$RICEDDARIOHOME:$PERL5LIB
# EMMA
export PATH=$RICEDDARIOHOME/EMMA/EMMA/bin:$RICEDDARIOHOME/EMMA/RAGE/bin:$PATH
export PERL5LIB=$RICEDDARIOHOME/EMMA:$PERL5LIB
# ISABEL
export PATH=$RICEDDARIOHOME/ISABEL/bin:$PATH
export PERL5LIB=$RICEDDARIOHOME/ISABEL:$PERL5LIB
# third parties
export PATH=$RICEDDARIOHOME/third_parties/GROMACS:$RICEDDARIOHOME/third_parties/MAQ:$RICEDDARIOHOME/third_parties/AMBER:$RICEDDARIOHOME/third_parties/Delphi:$RICEDDARIOHOME/third_parties/VMD:$RICEDDARIOHOME/third_parties/PyMol:$RICEDDARIOHOME/third_parties/MODELLER:$RICEDDARIOHOME/third_parties/BOWTIE:$PATH

